// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update7_Table_CustomerorderLine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update7_Table_CustomerorderLine));
        
        string IMigrationMetadata.Id
        {
            get { return "201703240151120_Update7_Table_CustomerorderLine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
