// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update8_Table_Article : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update8_Table_Article));
        
        string IMigrationMetadata.Id
        {
            get { return "201703240152279_update8_Table_Article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
