// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class up_Table_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up_Table_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "201703172325497_up_Table_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
