// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Delete_Table_statistic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Delete_Table_statistic));
        
        string IMigrationMetadata.Id
        {
            get { return "201703280009102_Delete_Table_statistic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
