// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update4_Table_CustomerOrderLine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update4_Table_CustomerOrderLine));
        
        string IMigrationMetadata.Id
        {
            get { return "201703232350106_Update4_Table_CustomerOrderLine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
